import type { Metadata } from "next";
import localFont from "next/font/local";
import Link from "next/link";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="flex flex-col min-h-screen">
          {" "}
          {/* {{ edit_2 }} */}
          <nav className="bg-gray-800 p-4">
            {" "}
            {/* {{ edit_3 }} */}
            <Link href="/" className="text-white">
              Home
            </Link>{" "}
            {/* {{ edit_4 }} */}
            <Link href="/notes" className="text-white">
              Notes
            </Link>{" "}
            {/* {{ edit_5 }} */}
          </nav>
          {children}
        </main>
      </body>
    </html>
  );
}
